apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: orders-node
spec:
  meshName: my-mesh
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: orders.default.svc.cluster.local
