apiVersion: v1
kind: Pod
metadata:
  name: ui-pod
  namespace: ui
  labels:
    app: ui
spec:
  containers:
  - name: ui-container
    image: alpine
    command: ["sh", "-c", "apk add --no-cache iputils && sleep 1000"]