apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - app1.yaml
  - app2.yaml
  - app3.yaml
  
patches:
  - path: service.yaml
    target:
      kind: Service
      name: ui
      namespace: ui