apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-microservices
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himanshuvaish/ecloudworx-eks.git
    targetRevision: dev
    path: k8s/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true